# Generated by Django 4.2.4 on 2023-08-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_description', models.TextField()),
                ('blog_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='navbar_items',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_tel',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_tel',
            field=models.CharField(max_length=15),
        ),
    ]
