# Generated by Django 4.2.4 on 2023-08-25 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0003_basket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
