# Generated by Django 4.2.4 on 2023-08-25 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='basket_product',
        ),
    ]
