# Generated by Django 4.2.4 on 2023-08-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_delete_basket_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_total_price', models.FloatField()),
                ('basket_total_product', models.IntegerField()),
            ],
        ),
    ]
