# Generated by Django 4.2.4 on 2023-08-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='basket_products',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
