# Generated by Django 4.2.4 on 2023-08-29 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_basket_basket_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='basket',
        ),
    ]
